<!-- START of: finna - content/street_search_fi.phtml -->
<?
    $this->headTitle($this->translate('street_search'));
    $this->content()->setHeading = false;
    $this->layout()->finnaMainHeader = false;

    $introText = '<div class="introduction"><h1 class="introductionText">' . $this->translate('street_search_header') . '</h1></div>';
    $button = '<div><span class="btn btn-primary" id="street-search-button">' . $this->transEsc('street_search_button') . '</span></div>';
    
    $this->layout()->searchbox = $introText . $button;
    
    $this->headScript()->appendFile('finna-street-search.js', 'text/javascript', '');
   
    $this->jsTranslations()->addStrings(
      array(
        'street_search_geolocation_inactive' => 'street_search_geolocation_inactive',
        'street_search_checking_for_geolocation' => 'street_search_checking_for_geolocation',
        'street_search_geolocation_available' => 'street_search_geolocation_available',
        'street_search_other_error' => 'street_search_other_error',
        'street_search_geolocation_inactive' => 'street_search_geolocation_inactive',
        'street_search_timeout' => 'street_search_timeout',
        'street_search_no_streetname_found' => 'street_search_no_streetname_found',
        'street_search_reversegeocode_unavailable' => 'street_search_reversegeocode_unavailable',
        'street_search_searching_for' => 'street_search_searching_for',
        'street_search_coordinates_found' => 'street_search_coordinates_found'
      )
    );
      
?>
<div class="row">
 <div class="col-md-10 col-lg-8">
   <ul id="street-search-output"></ul>
   <p>
     <?=$this->translate('street_search_info')?>
   </p>
 </div>
</div>
<!-- END of: finna - content/street_search_fi.phtml -->
